"""Agregar nuevas columnas

Revision ID: 3a53c6e4f719
Revises: 
Create Date: 2025-04-04 17:08:42.460581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a53c6e4f719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PROYECTO', sa.Column('fecha_prorroga_inicio', sa.Date(), nullable=True))
    op.add_column('PROYECTO', sa.Column('fecha_prorroga_fin', sa.Date(), nullable=True))
    op.drop_column('PROYECTO', 'tiempo_prorroga_meses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PROYECTO', sa.Column('tiempo_prorroga_meses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('PROYECTO', 'fecha_prorroga_fin')
    op.drop_column('PROYECTO', 'fecha_prorroga_inicio')
    # ### end Alembic commands ###
