"""Agregó nullable true a l campo prorroga inicio

Revision ID: b5420cc7800f
Revises: 3a53c6e4f719
Create Date: 2025-04-04 17:16:11.042400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5420cc7800f'
down_revision = '3a53c6e4f719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
